id = "catppuccin-blur"
name = "Catppuccin Blur"
schema_version = 1
version = "0.0.4"
authors = ["Kieran Klukas <me@dunkirk.sh>"]
description = "Catppuccin themes with blur (blue version with more defined sections)"
repository = "https://github.com/taciturnaxolotl/catppuccin-blur"
